### ISSUE TITLE
[Feature] Add support for binary downstream messages

### ISSUE THREAD

**Issue by richtier** [hishnash/channelsmultiplexer#1]
Thanks for making this :)

I solved the ["what to do if binary"](https://github.com/hishnash/channelsmultiplexer/blob/04e7fcf2092a4704ccdc1e7ea1fb9925ae2fea17/channelsmultiplexer/demultiplexer.py#L168) comment  in the following way:

```py
import base64

from channelsmultiplexer import AsyncJsonWebsocketDemultiplexer


class Demultiplexer(AsyncJsonWebsocketDemultiplexer):
    applications = {
      ...
    }

    async def websocket_send(self, message, stream_name):
        if 'bytes' in message:
            message['bytes'] = base64.b64encode(
                message['bytes']
            ).decode('ascii')
        elif 'text' in message:
            message['text'] = await self.decode_json(message['text'])
        data = {
            "stream": stream_name,
            "payload": message
        }
        await self.send_json(data)
```

then the browser does this in the websocket:
```js
  base64ToArrayBuffer(base64) {
    var binary_string = atob(base64);
    var bytes = new Uint8Array(binary_string.length);
    for (var i = 0; i < binary_string.length; i++)        {
        bytes[i] = binary_string.charCodeAt(i);
    }
    return bytes.buffer;
  }

  handleMessage = (event) => {
    const message = JSON.parse(event.data);
    let payload;
    // data in bytes is assumed to binary data encoded as base64
    if (message.payload.bytes) {
      payload = this.base64ToArrayBuffer(message.payload.bytes);
    } else if (message.payload.text) {
      payload = message.payload.text;
    }
    this.store.dispatch(
      actions.websocketMessageRecieve(message.stream, payload)
    );
  }

```

For context, this facilitates me to send audio data from Alexa back to the browser through the multiplexer to be played. I'm using `channelsmultiplexer` in conjunction with [Alexa Browser Client](https://github.com/richtier/alexa-browser-client) to make a super-powered open source alternative to Echo Show that runs on the browser of any tablet.

If you like the base64 encoding solution I can make a Pull Request to this repo adding it?

**Comment by hishnash** [comment]
sorry for the delayed response, interesting. Base64 seems however rather cpu (and data) heavy. 

you only need binary downstream (to the web browser)?  you not suggesting sending binary upstream (from the web browser)

what might be nicer is if the message coming from the upstream consumers is a binary web socket frame then the Demultiplexer could pass that downstream without any wrapping. 

(that would mean the client would not know which upstream handler send the data through)


--

alternivly and best I think would be to create a Proto-buff Demultiplexer this would let the `Demultiplexer` work like it were json but with binary data.

**Comment by hishnash** [comment]
@richtier do you just need to downstream (from the consumers to the browser) binary data?
