### ISSUE TITLE
Websocket close race condition

### ISSUE THREAD

**Issue by richtier** [hishnash/channelsmultiplexer#2]
When my consumer calls `self.close(code=3000)` the close event is sent to the browser, and the browser interprets "3000" to mean "authentication is required, redirect to login".

However, when `close()` is called, the demultiplexer calls `websocket_close` which removes that consumer's stream from `applications_accepting_frames`.

This creates a race condition if the browser sends a message to the server from that stream after `close()` is called, but before the browser receives the "websocket is closed" message.

When that happens the error "stream not mapped" occurs, resulting in the websocket being closed with non-3000 code so the browser does not know to redirect to login.

So this race condition causes any `self.close(code=...)` to trigger a close without a code.

**Comment by richtier** [comment]
I've worked around this problem by sending the "auth is required" instruction via a string rather than a close code.

**Comment by hishnash** [comment]
Sorry for the slow response on this, 

so to be clear one of the upstream consumers is calling `close` in this case what do you feel would be the best behaviour for the multiplexer?

a. Close the connection completely (killing all other upstream consumers)
b. Close just this upstream consumer  but keep the connection option (if at least one other upstream consumer is open)

currently, we do option `b`

see: https://github.com/hishnash/channelsmultiplexer/blob/master/channelsmultiplexer/demultiplexer.py#L187-L205
