### ISSUE TITLE
Support for Channels 3

### ISSUE THREAD

**Issue by johnthagen** [hishnash/channelsmultiplexer#4]
Does this project support Django Channels 3? It might be worth mentioning in the README until support is added if not compatible.

Thanks.

**Comment by hishnash** [comment]
I have a branch on my personal laptop I have been testing with Channels v3 I will try to finish up testing after work and get that released today/tomorrow.

**Comment by johnthagen** [comment]
Wow! Thanks for the quick response!

**Comment by hishnash** [comment]
version 0.0.3 is compatible to channels v3.

**Comment by johnthagen** [comment]
FYI the About in Github still says "v2". Perhaps that should be updated?
